language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

git:
  submodules: false

warnings_are_errors: true
env:
  global:
    - PKG_CXXFLAGS="-Wall -Wno-unused -pedantic"
    - _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - Enchufa2/covr

after_success:
  - Rscript -e 'covr::codecov()'
