# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install Rcpp
  - ./travis-tool.sh r_binary_install R6
  - ./travis-tool.sh r_binary_install magrittr
  - ./travis-tool.sh r_binary_install dplyr
  - ./travis-tool.sh r_binary_install tidyr
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install scales
  - ./travis-tool.sh r_binary_install testthat
  - ./travis-tool.sh r_binary_install knitr
  - ./travis-tool.sh r_binary_install rmarkdown
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change