language: r
sudo: required
warnings_are_errors: true
env:
  global:
    - PKG_CXXFLAGS += "-Wall -Wno-unused -pedantic"
    - CXX=clang++
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"

r_binary_packages:
  - Rcpp
  - R6
  - magrittr
  - dplyr
  - tidyr
  - ggplot2
  - scales
  - testthat
  - knitr
  - rmarkdown

after_success:
  - Rscript -e 'library(covr);coveralls()'
