language: R
sudo: false

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
env:
  global:
    - PKG_CXXFLAGS="-Wall -Wno-unused -pedantic"
    - _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
